version: "3"

services:
    server:
        build: ./server
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports: 
            - 5050:5000
        command: npm run dev
        volumes: 
            - ./server/src:/app/src
    mongodb:
        image: mongo
        volumes: 
            - ./data:/data/db
    client:
        build: ./client
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
            - FAST_REFRESH=false
            - WDS_SOCKET_PORT=8080
        ports:
            - 8080:3000
        volumes:
            - ./client/src:/app/src